# Generated by Django 3.2.7 on 2021-09-10 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('short_title', models.CharField(blank=True, max_length=50, null=True)),
                ('slug', models.URLField(blank=True, null=True)),
                ('img', models.URLField(blank=True, null=True)),
                ('icon', models.CharField(blank=True, max_length=50, null=True)),
                ('problems_count', models.IntegerField(default=0)),
                ('active', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('last_modified_data', models.DateField(auto_now=True)),
                ('last_modified_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
