# Generated by Django 3.2.7 on 2021-09-11 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_topic_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('short_title', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('priority', models.IntegerField(unique=True)),
                ('slug', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('problem_url', models.URLField()),
                ('solution_url', models.URLField()),
                ('video_url', models.URLField(blank=True, null=True)),
                ('active', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('last_modified_data', models.DateField(auto_now=True)),
                ('last_modified_time', models.DateTimeField(auto_now=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.topic')),
            ],
        ),
    ]
