# Generated by Django 3.2.7 on 2021-09-11 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20210911_2254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='problem',
        ),
        migrations.AddField(
            model_name='problem',
            name='topic',
            field=models.ManyToManyField(to='home.topic', verbose_name='all topics'),
        ),
    ]
