# Generated by Django 3.2.7 on 2021-09-12 10:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0007_auto_20210911_2322'),
    ]

    operations = [
        migrations.CreateModel(
            name='userProblemData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BooleanField(blank=True, choices=[(True, 'like'), (False, 'unlike')], null=True)),
                ('completed', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True)),
                ('viewed_solution', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('viewed_video', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('shared', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('last_modified_data', models.DateField(auto_now=True)),
                ('last_modified_time', models.DateTimeField(auto_now=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
