# Generated by Django 3.2.7 on 2021-09-12 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_userproblemdata_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='tag',
            field=models.CharField(blank=True, choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], max_length=20, null=True),
        ),
    ]
