# Generated by Django 3.2.7 on 2021-09-13 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_account_verification_faq'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='faq',
            new_name='myfaq',
        ),
    ]
