# Generated by Django 3.2.7 on 2021-09-13 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20210913_1729'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='userproblemdata',
            constraint=models.UniqueConstraint(fields=('user', 'problem'), name='name of constraint'),
        ),
    ]
