# Generated by Django 3.2.7 on 2021-09-13 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_userproblemdata_name of constraint'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='userproblemdata',
            name='name of constraint',
        ),
        migrations.AddConstraint(
            model_name='userproblemdata',
            constraint=models.UniqueConstraint(fields=('user', 'problem'), name='unique status of ever problem for a user'),
        ),
    ]
