# Generated by Django 3.2.7 on 2021-09-13 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_userproblemdata_like'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='userproblemdata',
            constraint=models.UniqueConstraint(fields=('user', 'problem'), name='unique status of ever problem for a user'),
        ),
    ]
