# Generated by Django 3.2.7 on 2021-09-13 18:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0018_userproblemdata_unique status of ever problem for a user'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='likes',
            field=models.ManyToManyField(related_name='blog_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
