# Generated by Django 3.2.7 on 2021-09-25 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_problem_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='priority',
            field=models.IntegerField(),
        ),
    ]
