# Generated by Django 3.2.7 on 2021-09-27 05:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0022_alter_problem_priority'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account_verification',
            old_name='verification_code',
            new_name='auth_token',
        ),
        migrations.AlterField(
            model_name='account_verification',
            name='account_status',
            field=models.BooleanField(choices=[(True, 'Active account'), (False, 'Blocked account')], default=True),
        ),
        migrations.AlterField(
            model_name='account_verification',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
